version: "3.8"

services:
  t3-proxy:
    build: .
    container_name: t3-proxy
    env_file: .env
    environment:
      - PROXY_BIND=0.0.0.0
      - CERT_KEY_PEM_PATH=/app/certs/key.pem
      - CERT_PEM_PATH=/app/certs/cert.pem
    volumes:
      - ./certs:/app/certs:ro
    ports:
      - "9222:9222"
      - "9223:9223"
    restart: unless-stopped
